name: 'Bootstrap'
description: 'Bootstrap action'
inputs:
  server-address: 
    description: 'Target server address'
    required: true
  registry-host:
    description: 'Registry domain'
    required: false
    default: '' # https://github.com/docker/login-action?tab=readme-ov-file#docker-hub
  registry-login:
    description: 'Registry username'
    required: true
  registry-password:
    description: 'Registry password'
    required: true
  server-ssh-key: 
    description: 'Server SSH key'
    required: true
  start-mysql:
    description: 'Whether MySQL should be started (default: false)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3 

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.server-ssh-key }}
        known_hosts: unnecessary

    - name: Add server to trusted
      shell: bash
      run: ssh-keyscan ${{ inputs.server-address }} >> ~/.ssh/known_hosts

    - uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry-host }}
        username: ${{ inputs.registry-login }}
        password: ${{ inputs.registry-password }}

    - name: Start MySQL
      if: inputs.start-mysql == 'true' || inputs.start-mysql == '1'
      shell: bash
      run: sudo systemctl start mysql.service

                    
          

